#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InterfaceSignatureAndSRI.Data
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ElectronicBillingDB")]
	public partial class DataContextLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertTypesVoucher(TypesVoucher instance);
    partial void UpdateTypesVoucher(TypesVoucher instance);
    partial void DeleteTypesVoucher(TypesVoucher instance);
    partial void InsertVoucher(Voucher instance);
    partial void UpdateVoucher(Voucher instance);
    partial void DeleteVoucher(Voucher instance);
    partial void InsertMySetting(MySetting instance);
    partial void UpdateMySetting(MySetting instance);
    partial void DeleteMySetting(MySetting instance);
    #endregion
		
		public DataContextLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataContextLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TypesVoucher> TypesVoucher
		{
			get
			{
				return this.GetTable<TypesVoucher>();
			}
		}
		
		public System.Data.Linq.Table<Voucher> Voucher
		{
			get
			{
				return this.GetTable<Voucher>();
			}
		}
		
		public System.Data.Linq.Table<MySetting> MySetting
		{
			get
			{
				return this.GetTable<MySetting>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TypesVoucher")]
	public partial class TypesVoucher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _TypesVoucherID;
		
		private string _NameVoucher;
		
		private string _Code;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTypesVoucherIDChanging(int value);
    partial void OnTypesVoucherIDChanged();
    partial void OnNameVoucherChanging(string value);
    partial void OnNameVoucherChanged();
    partial void OnCodeChanging(string value);
    partial void OnCodeChanged();
    #endregion
		
		public TypesVoucher()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypesVoucherID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int TypesVoucherID
		{
			get
			{
				return this._TypesVoucherID;
			}
			set
			{
				if ((this._TypesVoucherID != value))
				{
					this.OnTypesVoucherIDChanging(value);
					this.SendPropertyChanging();
					this._TypesVoucherID = value;
					this.SendPropertyChanged("TypesVoucherID");
					this.OnTypesVoucherIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameVoucher", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string NameVoucher
		{
			get
			{
				return this._NameVoucher;
			}
			set
			{
				if ((this._NameVoucher != value))
				{
					this.OnNameVoucherChanging(value);
					this.SendPropertyChanging();
					this._NameVoucher = value;
					this.SendPropertyChanged("NameVoucher");
					this.OnNameVoucherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="NChar(2) NOT NULL", CanBeNull=false)]
		public string Code
		{
			get
			{
				return this._Code;
			}
			set
			{
				if ((this._Code != value))
				{
					this.OnCodeChanging(value);
					this.SendPropertyChanging();
					this._Code = value;
					this.SendPropertyChanged("Code");
					this.OnCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Voucher")]
	public partial class Voucher : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _VoucherID;
		
		private int _TypesVoucherID;
		
		private int _IDRelationData;
		
		private string _ClaveAcceso;
		
		private string _Estado;
		
		private System.Nullable<System.DateTime> _FechaAutorizacion;
		
		private System.DateTime _FechaEmision;
		
		private System.Xml.Linq.XElement _Comprobante;
		
		private string _ErrorMesage;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVoucherIDChanging(int value);
    partial void OnVoucherIDChanged();
    partial void OnTypesVoucherIDChanging(int value);
    partial void OnTypesVoucherIDChanged();
    partial void OnIDRelationDataChanging(int value);
    partial void OnIDRelationDataChanged();
    partial void OnClaveAccesoChanging(string value);
    partial void OnClaveAccesoChanged();
    partial void OnEstadoChanging(string value);
    partial void OnEstadoChanged();
    partial void OnFechaAutorizacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaAutorizacionChanged();
    partial void OnFechaEmisionChanging(System.DateTime value);
    partial void OnFechaEmisionChanged();
    partial void OnComprobanteChanging(System.Xml.Linq.XElement value);
    partial void OnComprobanteChanged();
    partial void OnErrorMesageChanging(string value);
    partial void OnErrorMesageChanged();
    #endregion
		
		public Voucher()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VoucherID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int VoucherID
		{
			get
			{
				return this._VoucherID;
			}
			set
			{
				if ((this._VoucherID != value))
				{
					this.OnVoucherIDChanging(value);
					this.SendPropertyChanging();
					this._VoucherID = value;
					this.SendPropertyChanged("VoucherID");
					this.OnVoucherIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypesVoucherID", DbType="Int NOT NULL")]
		public int TypesVoucherID
		{
			get
			{
				return this._TypesVoucherID;
			}
			set
			{
				if ((this._TypesVoucherID != value))
				{
					this.OnTypesVoucherIDChanging(value);
					this.SendPropertyChanging();
					this._TypesVoucherID = value;
					this.SendPropertyChanged("TypesVoucherID");
					this.OnTypesVoucherIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDRelationData", DbType="Int NOT NULL")]
		public int IDRelationData
		{
			get
			{
				return this._IDRelationData;
			}
			set
			{
				if ((this._IDRelationData != value))
				{
					this.OnIDRelationDataChanging(value);
					this.SendPropertyChanging();
					this._IDRelationData = value;
					this.SendPropertyChanged("IDRelationData");
					this.OnIDRelationDataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClaveAcceso", DbType="VarChar(48) NOT NULL", CanBeNull=false)]
		public string ClaveAcceso
		{
			get
			{
				return this._ClaveAcceso;
			}
			set
			{
				if ((this._ClaveAcceso != value))
				{
					this.OnClaveAccesoChanging(value);
					this.SendPropertyChanging();
					this._ClaveAcceso = value;
					this.SendPropertyChanged("ClaveAcceso");
					this.OnClaveAccesoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string Estado
		{
			get
			{
				return this._Estado;
			}
			set
			{
				if ((this._Estado != value))
				{
					this.OnEstadoChanging(value);
					this.SendPropertyChanging();
					this._Estado = value;
					this.SendPropertyChanged("Estado");
					this.OnEstadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaAutorizacion", DbType="DateTime2")]
		public System.Nullable<System.DateTime> FechaAutorizacion
		{
			get
			{
				return this._FechaAutorizacion;
			}
			set
			{
				if ((this._FechaAutorizacion != value))
				{
					this.OnFechaAutorizacionChanging(value);
					this.SendPropertyChanging();
					this._FechaAutorizacion = value;
					this.SendPropertyChanged("FechaAutorizacion");
					this.OnFechaAutorizacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEmision", DbType="DateTime2 NOT NULL")]
		public System.DateTime FechaEmision
		{
			get
			{
				return this._FechaEmision;
			}
			set
			{
				if ((this._FechaEmision != value))
				{
					this.OnFechaEmisionChanging(value);
					this.SendPropertyChanging();
					this._FechaEmision = value;
					this.SendPropertyChanged("FechaEmision");
					this.OnFechaEmisionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comprobante", DbType="Xml NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Xml.Linq.XElement Comprobante
		{
			get
			{
				return this._Comprobante;
			}
			set
			{
				if ((this._Comprobante != value))
				{
					this.OnComprobanteChanging(value);
					this.SendPropertyChanging();
					this._Comprobante = value;
					this.SendPropertyChanged("Comprobante");
					this.OnComprobanteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorMesage", DbType="VarChar(MAX)")]
		public string ErrorMesage
		{
			get
			{
				return this._ErrorMesage;
			}
			set
			{
				if ((this._ErrorMesage != value))
				{
					this.OnErrorMesageChanging(value);
					this.SendPropertyChanging();
					this._ErrorMesage = value;
					this.SendPropertyChanged("ErrorMesage");
					this.OnErrorMesageChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MySetting")]
	public partial class MySetting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MySettingID;
		
		private System.Data.Linq.Binary _ImageLogo;
		
		private string _Email;
		
		private string _Password;
		
		private string _SMTP;
		
		private string _Port;
		
		private string _CompanyName;
		
		private string _Phone;
		
		private string _CellPhone;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMySettingIDChanging(int value);
    partial void OnMySettingIDChanged();
    partial void OnImageLogoChanging(System.Data.Linq.Binary value);
    partial void OnImageLogoChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnSMTPChanging(string value);
    partial void OnSMTPChanged();
    partial void OnPortChanging(string value);
    partial void OnPortChanged();
    partial void OnCompanyNameChanging(string value);
    partial void OnCompanyNameChanged();
    partial void OnPhoneChanging(string value);
    partial void OnPhoneChanged();
    partial void OnCellPhoneChanging(string value);
    partial void OnCellPhoneChanged();
    #endregion
		
		public MySetting()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MySettingID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MySettingID
		{
			get
			{
				return this._MySettingID;
			}
			set
			{
				if ((this._MySettingID != value))
				{
					this.OnMySettingIDChanging(value);
					this.SendPropertyChanging();
					this._MySettingID = value;
					this.SendPropertyChanged("MySettingID");
					this.OnMySettingIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageLogo", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ImageLogo
		{
			get
			{
				return this._ImageLogo;
			}
			set
			{
				if ((this._ImageLogo != value))
				{
					this.OnImageLogoChanging(value);
					this.SendPropertyChanging();
					this._ImageLogo = value;
					this.SendPropertyChanged("ImageLogo");
					this.OnImageLogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SMTP", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string SMTP
		{
			get
			{
				return this._SMTP;
			}
			set
			{
				if ((this._SMTP != value))
				{
					this.OnSMTPChanging(value);
					this.SendPropertyChanging();
					this._SMTP = value;
					this.SendPropertyChanged("SMTP");
					this.OnSMTPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Port", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string Port
		{
			get
			{
				return this._Port;
			}
			set
			{
				if ((this._Port != value))
				{
					this.OnPortChanging(value);
					this.SendPropertyChanging();
					this._Port = value;
					this.SendPropertyChanged("Port");
					this.OnPortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompanyName", DbType="VarChar(30)")]
		public string CompanyName
		{
			get
			{
				return this._CompanyName;
			}
			set
			{
				if ((this._CompanyName != value))
				{
					this.OnCompanyNameChanging(value);
					this.SendPropertyChanging();
					this._CompanyName = value;
					this.SendPropertyChanged("CompanyName");
					this.OnCompanyNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone", DbType="VarChar(20)")]
		public string Phone
		{
			get
			{
				return this._Phone;
			}
			set
			{
				if ((this._Phone != value))
				{
					this.OnPhoneChanging(value);
					this.SendPropertyChanging();
					this._Phone = value;
					this.SendPropertyChanged("Phone");
					this.OnPhoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CellPhone", DbType="VarChar(20)")]
		public string CellPhone
		{
			get
			{
				return this._CellPhone;
			}
			set
			{
				if ((this._CellPhone != value))
				{
					this.OnCellPhoneChanging(value);
					this.SendPropertyChanging();
					this._CellPhone = value;
					this.SendPropertyChanged("CellPhone");
					this.OnCellPhoneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
